### ISSUE TITLE
Examples using LLaMA-WebLINX, MindAct, Pix2Act, SeeAct

### ISSUE THREAD

**Issue by xhluca** [computer-agents/agent-studio#38]
Would love to see examples for using AgentStudio with some of the common models for autonomous web navigation ([Pix2Act](https://github.com/google-deepmind/pix2act), [MindAct](https://osu-nlp-group.github.io/Mind2Web/), [SeeAct](https://osu-nlp-group.github.io/SeeAct/)) and conversational webnav ([WebLINX models](https://huggingface.co/collections/McGill-NLP/weblinx-models-65c57d4afeeb282d1dcf8434) such as [SLLaMA-WL](https://huggingface.co/McGill-NLP/Sheared-LLaMA-2.7B-weblinx)).

**Comment by ltzheng** [comment]
Apologies for the delayed response. We’ve just released an updated version of the code and paper. While we appreciate these models, we chose not to integrate them into our code to maintain simplicity and minimalism, as even state-of-the-art VLMs like GPT-4 struggle with our tasks.
