### ISSUE TITLE
where i can download tasks.jsonl?

### ISSUE THREAD

**Issue by zhengshf** [computer-agents/agent-studio#50]
where is template like tasks.jsonl?
task_config_paths: dict = {
        # "desktop": "data/tasks/filesystem.jsonl",
        "desktop": "data/grounding/linux/os/tasks.jsonl",
    }

**Comment by ltzheng** [comment]
We've just released a new version of the online benchmark tasks. Now, the complete guidance for downloading task files and running evaluation is on our README.
