### ISSUE TITLE
ValueError: No prompt added

### ISSUE THREAD

**Issue by zhengshf** [computer-agents/agent-studio#51]
tasks：data/grounding/linux/os/tasks.jsonl

2024-07-09 14:28:30,722 ERROR run.py:294 -- [Unhandled Error] ValueError('No prompt added')]
2024-07-09 14:28:30,723 ERROR run.py:295 -- Traceback (most recent call last):
  File "/home/zsf/codebase/agent-studio/run.py", line 217, in eval_headless
    agent.reset(
  File "/home/zsf/codebase/agent-studio/agent_studio/agent/direct_agent.py", line 36, in reset
    self.system_prompt = composer.compose()
                         ^^^^^^^^^^^^^^^^^^
  File "/home/zsf/codebase/agent-studio/agent_studio/utils/prompt.py", line 115, in compose
    raise ValueError("No prompt added")
ValueError: No prompt added

**Comment by zhengshf** [comment]
python run.py --mode eval

**Comment by thisiszy** [comment]
Hi @zhengshf ,
Could you please provide more information? E.g. the agent_studio/config/config.py file. I tried in the GUI mode and can't reproduce your error.
![image](https://github.com/SkyworkAI/agent-studio/assets/43633145/1d7bb586-9aa2-4cd9-a8e0-a096749d41e1)

**Comment by zhengshf** [comment]
[config.py.zip](https://github.com/user-attachments/files/16153830/config.py.zip)

It was resolved when i add the code "composer.add("system_prompt")" in direct_agent.py before "composer.compose()".

**Comment by zhengshf** [comment]
The diff is "data/grounding/linux/os/tasks.jsonl" between of us.

my data/grounding/linux/os/tasks.jsonl is :
{"task_id": "15e27479-d6f5-4d67-aa2e-586c16f41277", "instruction": "Click the right bottom Power button", "evals": [], "visual": true}
{"task_id": "cfaa100d-8696-4e34-9468-43f719d9c4a9", "instruction": "Cancel", "evals": [], "visual": true}
{"task_id": "f0f074f9-1f75-44a9-b384-dc6afe8bd743", "instruction": "Click the Internet.", "evals": [], "visual": true}
{"task_id": "d884e2fc-b613-4687-b846-8a0bdadeef15", "instruction": "Click \"Image Viewer\"", "evals": [], "visual": true}

your is:
![image](https://github.com/SkyworkAI/agent-studio/assets/12720745/635eebd9-3971-49ea-bd5d-f3b5b6e627e4)

**Comment by ltzheng** [comment]
Sorry for the late response. We've just released a new version of the online benchmark tasks. Please visit our README and project page and try it. Hope you like our new documents and implementation.
