### ISSUE TITLE
Availability of recorded trajectory datasets

### ISSUE THREAD

**Issue by XinrunXu** [computer-agents/agent-studio#61]
I'm interested in using the recorded trajectory data mentioned in your README.md for [mention your intended use case, e.g., research, benchmarking]. The document mentions an example video showcasing the trajectory recording process, but I couldn't find any information about the availability of pre-recorded datasets.

Could you please tell me whether you plan to release any of the collected trajectory data? 

Thank you.

**Comment by ltzheng** [comment]
Thanks for your interest! We've just released a new version of our code. All online benchmark tasks and datasets can now be found on our README and project page.
